package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/alecthomas/kong"
	"github.com/bakito/crossplane-function-inventory-sdk/inventory"
	"github.com/stoewer/go-strcase"
)

const (
	generatedFileComment = `//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by tag-const-gen. DO NOT EDIT.

`
	generatedFilePrefix = "zz_generated_"
	generatedFileSuffix = "_const.go"
	filePermissions     = 0o600
	mapPrefix           = "Prefix"
)

type taggedField struct {
	sourceFields []string
	constName    string
	tagName      string
	tagValue     string
	isMap        bool
	typeName     string
}

type constGenerator struct {
	inputFile     string
	outputFile    string
	headerBuffer  bytes.Buffer
	contentBuffer bytes.Buffer
	imports       map[string]bool
}

// CLI defines the command line interface.
type CLI struct {
	Input string `help:"Input file path" required:"" short:"i" type:"existingfile"`
}

// Run executes the main logic.
func (cli *CLI) Run() error {
	generator := newConstGenerator(cli.Input)
	return generator.generateConstants()
}

func main() {
	cli := &CLI{}
	ctx := kong.Parse(cli,
		kong.Name("tag-const-gen"),
		kong.Description("Generate constants from struct tags"),
	)

	err := ctx.Run()
	if err != nil {
		log.Fatal(err)
	}
}

func buildConstName(typeName, tagType, name string) string {
	upperTypeName := strcase.UpperCamelCase(typeName)
	upperTagType := strcase.UpperCamelCase(tagType)
	// skip the type name prefix if it is already part of the tag type
	if strings.HasPrefix(upperTagType, upperTypeName) {
		upperTypeName = ""
	}

	return fmt.Sprintf("%s%s%s",
		upperTypeName,
		upperTagType,
		strcase.UpperCamelCase(name),
	)
}

func newConstGenerator(inputFile string) *constGenerator {
	fileName := filepath.Base(inputFile)
	dirName := filepath.Dir(inputFile)
	return &constGenerator{
		imports:   make(map[string]bool),
		inputFile: inputFile,
		outputFile: filepath.Join(
			dirName,
			generatedFilePrefix+strings.TrimSuffix(fileName, ".go")+generatedFileSuffix,
		),
	}
}

func (g *constGenerator) generateConstants() error {
	fSet := token.NewFileSet()
	node, err := parser.ParseFile(fSet, g.inputFile, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("failed to parse input file: %w", err)
	}

	g.writeHeader(node.Name.Name)
	g.processStructs(node)
	g.addImports()

	return g.writeToFile()
}

func (g *constGenerator) writeHeader(packageName string) {
	fmt.Fprint(&g.headerBuffer, generatedFileComment)
	fmt.Fprintf(&g.headerBuffer, "package %s\n\n", packageName)
}

func (g *constGenerator) addImports() {
	switch len(g.imports) {
	case 0:
		return
	case 1:
		for packageName := range g.imports {
			fmt.Fprintf(&g.headerBuffer, "import %q\n\n", packageName)
		}
	default:
		fmt.Fprint(&g.headerBuffer, "import (\n")
		for packageName := range g.imports {
			fmt.Fprintf(&g.headerBuffer, "\t%q\n", packageName)
		}
		fmt.Fprint(&g.headerBuffer, ")\n\n")
	}
}

func (g *constGenerator) processStructs(node *ast.File) {
	ast.Inspect(node, func(n ast.Node) bool {
		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}

		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			return true
		}

		g.processStructFields(typeSpec.Name.Name, structType.Fields.List)

		return true
	})
}

func (g *constGenerator) processStructFields(
	typeName string,
	fields []*ast.Field,
) {
	taggedFields := make(map[string]*taggedField)
	var taggedFieldsOrder []string

	for _, field := range fields {
		tf := g.parseTag(typeName, field)
		if tf == nil {
			continue
		}
		constName := tf.constName
		if existing, ok := taggedFields[constName]; ok {
			existing.sourceFields = append(existing.sourceFields, tf.sourceFields[0])
		} else {
			taggedFields[constName] = tf
			taggedFieldsOrder = append(taggedFieldsOrder, constName)
		}
	}

	anyMapDetected := g.emitConstants(taggedFields, taggedFieldsOrder)
	if anyMapDetected {
		g.emitConvenienceFunctions(taggedFields, taggedFieldsOrder)
	}
}

func (g *constGenerator) emitConstants(taggedFields map[string]*taggedField, order []string) bool {
	withMaps := false
	if len(taggedFields) == 0 {
		return false
	}
	fmt.Fprint(&g.contentBuffer, "const (\n")
	for _, key := range order {
		tf := taggedFields[key]
		g.writeConstantDefinition(tf)
		withMaps = withMaps || tf.isMap
	}
	fmt.Fprint(&g.contentBuffer, ")\n")
	return withMaps
}

func (g *constGenerator) emitConvenienceFunctions(
	taggedFields map[string]*taggedField,
	order []string,
) {
	for _, key := range order {
		tf := taggedFields[key]
		if tf.isMap {
			g.writeConvenienceFunctions(tf)
		}
	}
}

func (g *constGenerator) parseTag(typeName string, field *ast.Field) *taggedField {
	if field == nil || field.Tag == nil || len(field.Names) == 0 {
		return nil
	}
	tagStr := strings.Trim(field.Tag.Value, "`")
	tagVal := reflect.StructTag(tagStr).Get(inventory.TagKey)
	if tagVal == "" || !strings.Contains(tagVal, inventory.TagSeparator) {
		return nil
	}

	parts := strings.Split(tagVal, inventory.TagSeparator)
	if len(parts) < 2 || !isAllowedTagType(parts[0]) {
		return nil
	}

	_, isMap := field.Type.(*ast.MapType)
	fieldName := field.Names[0].String()

	constName := buildConstName(typeName, parts[0], parts[1])
	return &taggedField{
		constName:    constName,
		typeName:     typeName,
		sourceFields: []string{fieldName},
		tagName:      parts[0],
		tagValue:     parts[1],
		isMap:        isMap,
	}
}

var allowedTagTypes = map[string]bool{
	inventory.TagTypeRequired:         true,
	inventory.TagTypeObservedComposed: true,
	inventory.TagTypeDesiredComposed:  true,
}

func isAllowedTagType(tagType string) bool {
	_, ok := allowedTagTypes[tagType]
	return ok
}

func (g *constGenerator) writeConstantDefinition(tf *taggedField) {
	constName := tf.constName
	if tf.isMap {
		constName += mapPrefix
	}
	if len(tf.sourceFields) == 1 {
		fmt.Fprintf(
			&g.contentBuffer,
			"\t// %s name generated from tag '%s' of field '%s.%s'.\n",
			constName,
			tf.tagName,
			tf.typeName,
			tf.sourceFields[0],
		)
	} else {
		fieldNames := make([]string, len(tf.sourceFields))
		for i, field := range tf.sourceFields {
			fieldNames[i] = fmt.Sprintf("'%s.%s'", tf.typeName, field)
		}
		fmt.Fprintf(
			&g.contentBuffer,
			"\t// %s name generated from tag '%s' of fields %s.\n",
			constName,
			tf.tagName,
			strings.Join(fieldNames, ", "),
		)
	}
	fmt.Fprintf(&g.contentBuffer, "\t%s = %q\n", constName, tf.tagValue)
}

func (g *constGenerator) writeConvenienceFunctions(tf *taggedField) {
	g.imports["fmt"] = true
	fmt.Fprintln(&g.contentBuffer)
	fmt.Fprintf(
		&g.contentBuffer,
		"// %s convenience function to generate prefixed names\n",
		tf.constName,
	)
	fmt.Fprintf(&g.contentBuffer, "func %s(name string) string {\n", tf.constName)
	fmt.Fprintf(
		&g.contentBuffer,
		"\t return fmt.Sprintf(%q, name)\n",
		tf.tagValue+"%s",
	)
	fmt.Fprint(&g.contentBuffer, "}\n")
}

func (g *constGenerator) writeToFile() error {
	formattedBytes, err := format.Source(append(g.headerBuffer.Bytes(), g.contentBuffer.Bytes()...))
	if err != nil {
		return fmt.Errorf("failed to format output: %w", err)
	}

	if err := os.WriteFile(g.outputFile, formattedBytes, filePermissions); err != nil {
		return fmt.Errorf("failed to write output file: %w", err)
	}
	return nil
}
